/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.8 at Sat Dec 18 17:56:56 2021. */

#ifndef PB_LEDTAPE_PB_H_INCLUDED
#define PB_LEDTAPE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LedTape {
    pb_callback_t diodes;
/* @@protoc_insertion_point(struct:LedTape) */
} LedTape;

typedef struct _LedTape_Diode {
    int32_t id;
    int32_t r;
    int32_t g;
    int32_t b;
/* @@protoc_insertion_point(struct:LedTape_Diode) */
} LedTape_Diode;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LedTape_init_default                     {{{NULL}, NULL}}
#define LedTape_Diode_init_default               {0, 0, 0, 0}
#define LedTape_init_zero                        {{{NULL}, NULL}}
#define LedTape_Diode_init_zero                  {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LedTape_diodes_tag                       1
#define LedTape_Diode_id_tag                     1
#define LedTape_Diode_r_tag                      2
#define LedTape_Diode_g_tag                      3
#define LedTape_Diode_b_tag                      4

/* Struct field encoding specification for nanopb */
extern const pb_field_t LedTape_fields[2];
extern const pb_field_t LedTape_Diode_fields[5];

/* Maximum encoded size of messages (where known) */
/* LedTape_size depends on runtime parameters */
#define LedTape_Diode_size                       44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LEDTAPE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
